### ISSUE TITLE
执行无效，发现x_xhh_tokenid每次app启动都会不一样

### ISSUE THREAD

**Issue by just-re** [1398440232/BlackboxSign#1]
找到1个账号
--开始做签到任务--
账号1 -> 签到成功！
--开始做分享贴子任务--
{ msg: '非法请求', result: {}, status: 'failed' }
--开始做分享游戏详情任务--
--开始做分享游戏评价任务--
{ msg: '非法请求', result: {}, status: 'failed' }
{ msg: '非法请求', result: {}, status: 'failed' }
--开始游戏榜单停留10s任务--
{ msg: '非法请求', result: {}, status: 'failed' }

**Comment by 1398440232** [comment]
可以提供一下小黑盒的版本号吗，我的是1.3.336，x_xhh_tokenid不会变

**Comment by 1398440232** [comment]
> 找到1个账号 --开始做签到任务-- 账号1 -> 签到成功！ --开始做分享贴子任务-- { msg: '非法请求', result: {}, status: 'failed' } --开始做分享游戏详情任务-- --开始做分享游戏评价任务-- { msg: '非法请求', result: {}, status: 'failed' } { msg: '非法请求', result: {}, status: 'failed' } --开始游戏榜单停留10s任务-- { msg: '非法请求', result: {}, status: 'failed' }
可以提供一下小黑盒的版本号吗，我的是1.3.336，x_xhh_tokenid不会变

**Comment by 1398440232** [comment]
> 找到1个账号 --开始做签到任务-- 账号1 -> 签到成功！ --开始做分享贴子任务-- { msg: '非法请求', result: {}, status: 'failed' } --开始做分享游戏详情任务-- --开始做分享游戏评价任务-- { msg: '非法请求', result: {}, status: 'failed' } { msg: '非法请求', result: {}, status: 'failed' } --开始游戏榜单停留10s任务-- { msg: '非法请求', result: {}, status: 'failed' }

可以提供一下小黑盒的版本号吗，我的是1.3.336，x_xhh_tokenid不会变

**Comment by just-re** [comment]
1.3.340

**Comment by 1398440232** [comment]
> 1.3.340

我测试了1.3.341的版本，没有问题，多执行几次试试

**Comment by 1398440232** [comment]
检查cookie格式填对了没



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: just ***@***.***&gt;
发送时间: 2024年11月16日 17:13
收件人: 1398440232/BlackboxSign ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [1398440232/BlackboxSign] 执行无效，发现x_xhh_tokenid每次app启动都会不一样 (Issue #1)





 
找到1个账号
 --开始做签到任务--
 账号1 -&gt; 签到成功！
 --开始做分享贴子任务--
 { msg: '非法请求', result: {}, status: 'failed' }
 --开始做分享游戏详情任务--
 --开始做分享游戏评价任务--
 { msg: '非法请求', result: {}, status: 'failed' }
 { msg: '非法请求', result: {}, status: 'failed' }
 --开始游戏榜单停留10s任务--
 { msg: '非法请求', result: {}, status: 'failed' }
